server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: https://discovery-server-production.up.railway.app/eureka
spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:56745/auth_db?user=root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mNvmHFuvykgpBQNzlxFiVivFVwmRGTGP
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  expiration-refresh-token: 5184000
  secretKey: cONZe0ovkAXrizdcbS69hVcQDxmMBLqkoODh846Opdk=