server:
  port: ${PORT:9001}
api:
  prefix: api/v1
spring:
  application:
    name: Auth-Service
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://midtob-service-nguyenviet3057.f.aivencloud.com:28776/auth_db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:avnadmin}
    password: ${DATABASE_PASSWORD:AVNS_ctJSYzosDSyudfsXdza}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  expiration: 2592000
  expiration-refresh-token: 5184000
  secretKey: cONZe0ovkAXrizdcbS69hVcQDxmMBLqkoODh846Opdk=